# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# git-complation
if [ -f $HOME/.git-completion.bash ]; then
	. $HOME/.git-completion.bash
fi

if [ -f $HOME/.git-prompt.sh ]; then
	. $HOME/.git-prompt.sh
fi

# User specific aliases and functions
PS1='\u@\h[$PWD$(__git_ps1)]\$ '
set -o vi

alias sudo='sudo -E '
