---
- name: create ssh dir
  file:
    path=~/.ssh
    state=directory
    mode=0700

- name: create id_rsa
  template:
    src=id_rsa.j2
    dest=~/.ssh/id_rsa

- name: change permission id_rsa
  file:
    path=~/.ssh/id_rsa
    mode=0600

- name: create authorized_key
  authorized_key:
    user="{{ ansible_user_id }}"
    key="{{ ssh_key_public_key_string }}"

